# OA: (0)Dye, Circuits, Plastic, Hamburger, (4)Filament, 
# Patch, Dumbbells, Charcoal, Feather, (9)Resin, Shard, 
# Tough Stuff, Iron Filament, Polish, (14)Ectoplasm, Pebble, Perfection,
# Poison, Ash, (19)New Tag, Vibrations, Water, Goo, Rubber, (24)Dust, 
# Ice, Crystalline Shard, Strange Capacitor, Glint, (29)Cellulose, 
# Magma Ball, Ghastly Eye, Jotunn Shard

mat_called_name = [
    "Painted",
    "Electronic",
    "Plastic",
    "Edible",
    "Emits Light",
    "Made With Fabric",
    "Heavy",
    "Dull",
    "Light",
    "Organic",
    "Glass",
    "Hard",
    "Magnetic",
    "Shiny",
    "Haunted",
    "Stony",
    "Pure",
    "Poisonous",
    "Hot",
    "Fresh",
    "Makes Noise",
    "Wet",
    "Slimy",
    "Bouncy",
    "Ancient",
    "Cold",
    "Glass",
    "Electronic",
    "Shiny",
    "Plastic",
    "Hot",
    "Haunted",
    "Cold"
]

mat_display_name = [
    "Dyes",
    "Circuits",
    "Plastics",
    "Hamburgers",
    "Filaments",
    "Patches",
    "Dumbbells",
    "Charcoal",
    "Feathers",
    "Resin",
    "Shards",
    "Tough Stuff",
    "Iron Filaments",
    "Polish",
    "Ectoplasm",
    "Pebbles",
    "Perfections",
    "Poison",
    "Ash",
    "New Tags",
    "Vibrations",
    "Water",
    "Goo",
    "Rubber",
    "Dust",
    "Ice",
    "Crystalline Shards",
    "Strange Capacitors",
    "Glint",
    "Cellulose",
    "Magma Balls",
    "Ghastly Eyes",
    "Jotuun Shards"
]